/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'timestamp' : IDL.Int,
  'interestLevel' : IDL.Text,
});

export const idlService = IDL.Service({
  'findLeadsByCompany' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
  'findLeadsByInterestLevel' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getLeadById' : IDL.Func([IDL.Nat], [Lead], ['query']),
  'getLeadsSortedByTimestamp' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'submitLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'timestamp' : IDL.Int,
    'interestLevel' : IDL.Text,
  });
  
  return IDL.Service({
    'findLeadsByCompany' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
    'findLeadsByInterestLevel' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Lead)],
        ['query'],
      ),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getLeadById' : IDL.Func([IDL.Nat], [Lead], ['query']),
    'getLeadsSortedByTimestamp' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'submitLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };